import puppeteer from 'puppeteer';

interface FieldValue {
  [key: string]: string | number;
}

interface DocumentGenerationOptions {
  templateTitle: string;
  templateContent: string;
  fieldValues: FieldValue;
  stateId: string;
}

// HTML escape function to prevent XSS/injection attacks
function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;")
    .replace(/\//g, "&#x2F;");
}

export async function generateDocument(options: DocumentGenerationOptions): Promise<Buffer> {
  const { templateTitle, templateContent, fieldValues, stateId } = options;

  // Create HTML content with filled fields
  const htmlContent = generateHTMLFromTemplate(templateTitle, templateContent, fieldValues, stateId);

  // Launch headless browser
  // NOTE: Using system Chromium for stability in Replit environment.
  // Running in --no-sandbox mode for Replit environment compatibility.
  // Security is maintained through comprehensive HTML escaping of all user input.
  // All user input is HTML-escaped before rendering to prevent injection attacks.
  const browser = await puppeteer.launch({
    headless: true,
    executablePath: '/nix/store/zi4f80l169xlmivz8vja8wlphq74qqk0-chromium-125.0.6422.141/bin/chromium',
    args: [
      '--no-sandbox', // Required for Replit containerized environment
      '--disable-setuid-sandbox', // Required for Replit containerized environment
      '--disable-dev-shm-usage', // Required for containerized environments
      '--disable-gpu', // Not needed for PDF generation
      '--single-process', // More stable in containerized environments
      '--no-zygote' // More stable in containerized environments
    ]
  });

  try {
    const page = await browser.newPage();
    
    // Set content
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: 'Letter',
      printBackground: true,
      margin: {
        top: '0.75in',
        right: '0.75in',
        bottom: '0.75in',
        left: '0.75in',
      }
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}

function generateHTMLFromTemplate(
  templateTitle: string,
  templateContent: string,
  fieldValues: FieldValue,
  stateId: string
): string {
  // SECURITY: For MVP, we ONLY use default template generation with fully escaped values.
  // templateContent should always be empty. If it's not empty, we ignore it to prevent injection.
  // Future custom templates must use a safe templating engine with auto-escaping.
  
  // Sanitize ALL inputs to prevent HTML injection
  const safeTitle = escapeHtml(templateTitle);
  const safeStateId = escapeHtml(stateId);
  
  // ALWAYS use default template generation (never trust templateContent from database)
  let filledContent = generateDefaultTemplateContent(safeTitle, fieldValues, safeStateId);
  
  // For safety, still escape any {{fieldId}} placeholders if they exist
  // (though default generator doesn't use this pattern)
  Object.entries(fieldValues).forEach(([fieldId, value]) => {
    const placeholder = new RegExp(`{{${fieldId}}}`, 'g');
    const escapedValue = escapeHtml(String(value));
    filledContent = filledContent.replace(placeholder, escapedValue);
  });

  // Wrap in proper HTML structure with styling
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle}</title>
  <style>
    @page {
      size: Letter;
      margin: 0.75in;
    }
    
    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      margin: 0;
      padding: 0;
    }
    
    h1 {
      font-size: 18pt;
      font-weight: bold;
      text-align: center;
      margin-bottom: 24pt;
      text-transform: uppercase;
    }
    
    h2 {
      font-size: 14pt;
      font-weight: bold;
      margin-top: 20pt;
      margin-bottom: 10pt;
      border-bottom: 1px solid #333;
      padding-bottom: 4pt;
    }
    
    h3 {
      font-size: 12pt;
      font-weight: bold;
      margin-top: 16pt;
      margin-bottom: 8pt;
    }
    
    p {
      margin-bottom: 12pt;
      text-align: justify;
    }
    
    .field-value {
      font-weight: bold;
      text-decoration: underline;
    }
    
    .signature-line {
      margin-top: 40pt;
      border-top: 1px solid #000;
      width: 300pt;
      display: inline-block;
    }
    
    .signature-block {
      margin-top: 30pt;
      page-break-inside: avoid;
    }
    
    .footer {
      margin-top: 40pt;
      font-size: 10pt;
      color: #666;
      text-align: center;
      border-top: 1px solid #ccc;
      padding-top: 12pt;
    }
  </style>
</head>
<body>
  ${filledContent}
  
  <div class="footer">
    Document generated by LeaseShield App | ${safeStateId} | ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `;
}

function getStateDisclosures(stateId: string, templateTitle: string): string {
  const disclosures: Record<string, string> = {
    UT: `
      <h2>Utah State-Specific Disclosures</h2>
      <h3>Fair Housing Notice</h3>
      <p>In accordance with the Fair Housing Act and Utah Fair Housing Act, it is illegal to discriminate in the sale, rental, or financing of housing, or in the provision of real estate services, because of race, color, religion, sex, handicap, familial status, national origin, or sexual orientation.</p>
      <h3>Radon Gas</h3>
      <p>Radon is a naturally occurring radioactive gas that may accumulate in buildings. Testing for radon is recommended but not required.</p>
      <h3>Lead-Based Paint (if built before 1978)</h3>
      <p>Housing built before 1978 may contain lead-based paint. Lead from paint, paint chips, and dust can pose health hazards, particularly for young children. Contact local health authorities for information on lead hazards.</p>
    `,
    TX: `
      <h2>Texas State-Specific Disclosures</h2>
      <h3>Fair Housing Notice</h3>
      <p>It is illegal to refuse to rent, to refuse to negotiate for the rental, or in any other manner to discriminate in connection with the offering, advertising, leasing, or in the provision of any facilities or services of the property, because of race, color, religion, sex, national origin, handicap, or familial status.</p>
      <h3>Lead-Based Paint Disclosure (Pre-1978 Properties)</h3>
      <p>If the property was built before January 1, 1978, landlord must provide all available records and reports regarding lead-based paint and lead-based paint hazards.</p>
      <h3>Residential Tenancy Act Rights and Responsibilities</h3>
      <p>Tenant rights and landlord duties are governed by the Texas Property Code, Chapter 92.</p>
    `,
    ND: `
      <h2>North Dakota State-Specific Disclosures</h2>
      <h3>Fair Housing Compliance</h3>
      <p>Complies with Fair Housing Act and North Dakota Fair Housing Act. It is illegal to refuse housing or discriminate based on protected class status.</p>
      <h3>Security Deposit Handling</h3>
      <p>Security deposits must be held in accordance with North Dakota Century Code Section 47-16-01 et seq.</p>
      <h3>Right to Counsel</h3>
      <p>Tenant has the right to be represented by an attorney in any legal proceedings regarding this lease.</p>
    `,
    SD: `
      <h2>South Dakota State-Specific Disclosures</h2>
      <h3>Fair Housing Statement</h3>
      <p>Fair housing is a right guaranteed by federal and state law. It is illegal to discriminate in the rental of housing because of race, color, creed, religion, sex, national origin, disability, familial status, or sexual orientation.</p>
      <h3>Lead-Based Paint Notice (if applicable)</h3>
      <p>Properties built before 1978 may contain lead-based paint hazards. Landlord is required to disclose all known information regarding lead-based paint.</p>
      <h3>Landlord and Tenant Responsibilities</h3>
      <p>Rights and responsibilities are governed by South Dakota Codified Law Chapter 43-32.</p>
    `
  };

  return disclosures[stateId] || `
    <h2>Mandatory Disclosures</h2>
    <h3>Fair Housing Notice</h3>
    <p>Housing is offered without regard to protected characteristics under federal and state fair housing laws.</p>
  `;
}

function generateDefaultTemplateContent(
  safeTitle: string,
  fieldValues: FieldValue,
  safeStateId: string
): string {
  // Generate a default template based on common patterns
  // NOTE: safeTitle and safeStateId are already HTML-escaped
  const sections: string[] = [];
  
  sections.push(`<h1>${safeTitle}</h1>`);
  
  // Group fields by category
  const categories = new Map<string, Array<[string, any]>>();
  
  Object.entries(fieldValues).forEach(([fieldId, value]) => {
    // Infer category from field ID (simple heuristic)
    let category = 'General Information';
    if (fieldId.includes('landlord')) category = 'Landlord Information';
    else if (fieldId.includes('tenant')) category = 'Tenant Information';
    else if (fieldId.includes('property')) category = 'Property Details';
    else if (fieldId.includes('rent') || fieldId.includes('deposit') || fieldId.includes('fee')) category = 'Financial Terms';
    else if (fieldId.includes('lease') || fieldId.includes('date')) category = 'Lease Terms';
    
    if (!categories.has(category)) {
      categories.set(category, []);
    }
    categories.get(category)!.push([fieldId, value]);
  });
  
  // Generate sections (with HTML escaping for security)
  categories.forEach((fields, category) => {
    const safeCategory = escapeHtml(category);
    sections.push(`<h2>${safeCategory}</h2>`);
    fields.forEach(([fieldId, value]) => {
      const label = fieldIdToLabel(fieldId);
      const safeLabel = escapeHtml(label);
      const safeValue = escapeHtml(String(value));
      sections.push(`<p><strong>${safeLabel}:</strong> <span class="field-value">${safeValue}</span></p>`);
    });
  });
  
  // Add state-specific disclosures for lease agreements, rental applications, and notices
  const titleLower = safeTitle.toLowerCase();
  if (titleLower.includes('lease') || titleLower.includes('agreement') || 
      titleLower.includes('rental application') || titleLower.includes('notice') ||
      titleLower.includes('checklist')) {
    sections.push(getStateDisclosures(safeStateId, safeTitle));
  }
  
  // Add signature blocks for leases and agreements
  if (titleLower.includes('lease') || titleLower.includes('agreement')) {
    sections.push(`
      <div class="signature-block">
        <h2>Signatures</h2>
        <p>By signing below, the parties acknowledge that they have read, understood, and agree to the terms outlined in this document.</p>
        
        <p style="margin-top: 30pt;">
          <strong>Landlord:</strong><br>
          Signature: <span class="signature-line"></span><br>
          Date: _________________
        </p>
        
        <p style="margin-top: 30pt;">
          <strong>Tenant:</strong><br>
          Signature: <span class="signature-line"></span><br>
          Date: _________________
        </p>
      </div>
    `);
  }
  
  return sections.join('\n');
}

function fieldIdToLabel(fieldId: string): string {
  // Convert camelCase to Title Case
  return fieldId
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (str) => str.toUpperCase())
    .trim();
}
