import puppeteer from 'puppeteer';

interface FieldValue {
  [key: string]: string | number;
}

interface DocumentGenerationOptions {
  templateTitle: string;
  templateContent: string;
  fieldValues: FieldValue;
  stateId: string;
}

// HTML escape function to prevent XSS/injection attacks
function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;")
    .replace(/\//g, "&#x2F;");
}

export async function generateDocument(options: DocumentGenerationOptions): Promise<Buffer> {
  const { templateTitle, templateContent, fieldValues, stateId } = options;

  // Create HTML content with filled fields
  const htmlContent = generateHTMLFromTemplate(templateTitle, templateContent, fieldValues, stateId);

  // Launch headless browser
  // NOTE: Using system Chromium for stability in Replit environment.
  // Running in --no-sandbox mode for Replit environment compatibility.
  // Security is maintained through comprehensive HTML escaping of all user input.
  // All user input is HTML-escaped before rendering to prevent injection attacks.
  const browser = await puppeteer.launch({
    headless: true,
    executablePath: '/nix/store/zi4f80l169xlmivz8vja8wlphq74qqk0-chromium-125.0.6422.141/bin/chromium',
    args: [
      '--no-sandbox', // Required for Replit containerized environment
      '--disable-setuid-sandbox', // Required for Replit containerized environment
      '--disable-dev-shm-usage', // Required for containerized environments
      '--disable-gpu', // Not needed for PDF generation
      '--single-process', // More stable in containerized environments
      '--no-zygote' // More stable in containerized environments
    ]
  });

  try {
    const page = await browser.newPage();
    
    // Set content
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: 'Letter',
      printBackground: true,
      margin: {
        top: '0.75in',
        right: '0.75in',
        bottom: '0.75in',
        left: '0.75in',
      }
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}

function generateHTMLFromTemplate(
  templateTitle: string,
  templateContent: string,
  fieldValues: FieldValue,
  stateId: string
): string {
  // SECURITY: For MVP, we ONLY use default template generation with fully escaped values.
  // templateContent should always be empty. If it's not empty, we ignore it to prevent injection.
  // Future custom templates must use a safe templating engine with auto-escaping.
  
  // Sanitize ALL inputs to prevent HTML injection
  const safeTitle = escapeHtml(templateTitle);
  const safeStateId = escapeHtml(stateId);
  
  // ALWAYS use default template generation (never trust templateContent from database)
  let filledContent = generateDefaultTemplateContent(safeTitle, fieldValues, safeStateId);
  
  // For safety, still escape any {{fieldId}} placeholders if they exist
  // (though default generator doesn't use this pattern)
  Object.entries(fieldValues).forEach(([fieldId, value]) => {
    const placeholder = new RegExp(`{{${fieldId}}}`, 'g');
    const escapedValue = escapeHtml(String(value));
    filledContent = filledContent.replace(placeholder, escapedValue);
  });

  // Wrap in proper HTML structure with styling
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle}</title>
  <style>
    @page {
      size: Letter;
      margin: 0.75in;
    }
    
    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      margin: 0;
      padding: 0;
    }
    
    h1 {
      font-size: 18pt;
      font-weight: bold;
      text-align: center;
      margin-bottom: 24pt;
      text-transform: uppercase;
    }
    
    h2 {
      font-size: 14pt;
      font-weight: bold;
      margin-top: 20pt;
      margin-bottom: 10pt;
      border-bottom: 1px solid #333;
      padding-bottom: 4pt;
    }
    
    h3 {
      font-size: 12pt;
      font-weight: bold;
      margin-top: 16pt;
      margin-bottom: 8pt;
    }
    
    p {
      margin-bottom: 12pt;
      text-align: justify;
    }
    
    .field-value {
      font-weight: bold;
      text-decoration: underline;
    }
    
    .signature-line {
      margin-top: 40pt;
      border-top: 1px solid #000;
      width: 300pt;
      display: inline-block;
    }
    
    .signature-block {
      margin-top: 30pt;
      page-break-inside: avoid;
    }
    
    .footer {
      margin-top: 40pt;
      font-size: 10pt;
      color: #666;
      text-align: center;
      border-top: 1px solid #ccc;
      padding-top: 12pt;
    }
  </style>
</head>
<body>
  ${filledContent}
  
  <div class="footer">
    Document generated by LeaseShield App | ${safeStateId} | ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `;
}

function getComprehensiveLeaseContent(stateId: string, fieldValues: FieldValue): string {
  return `
    <h2>1. TERM OF LEASE</h2>
    <p>This Residential Lease Agreement ("Lease") is entered into as of ${escapeHtml(String(fieldValues.leaseStartDate) || '[DATE]')} ("Commencement Date") between the undersigned Landlord and Tenant(s) for the rental of the property located at ${escapeHtml(String(fieldValues.propertyAddress) || '[ADDRESS]')}, ${escapeHtml(String(fieldValues.propertyCity) || '[CITY]')}, ${stateId} ${escapeHtml(String(fieldValues.propertyZip) || '[ZIP]')} ("Premises"). This Lease shall commence on ${escapeHtml(String(fieldValues.leaseStartDate) || '[START DATE]')} and shall terminate at 11:59 PM on ${escapeHtml(String(fieldValues.leaseEndDate) || '[END DATE]')} unless sooner terminated or further extended in writing by mutual agreement of both parties.</p>

    <h2>2. PARTIES AND OCCUPANTS</h2>
    <p>Landlord: ${escapeHtml(String(fieldValues.landlordName) || '[LANDLORD NAME]')}, residing at ${escapeHtml(String(fieldValues.landlordAddress) || '[ADDRESS]')}. Tenant(s): ${escapeHtml(String(fieldValues.tenantName) || '[TENANT NAME]')}. All occupants of the Premises, whether family members, friends, or guests staying more than fourteen (14) consecutive days or thirty (30) days in any calendar year, must be approved in writing by Landlord. Unauthorized occupants shall constitute a material breach of this Lease.</p>

    <h2>3. RENT AND PAYMENT TERMS</h2>
    <p>3.1 Monthly Rent: Tenant agrees to pay Landlord the sum of $${escapeHtml(String(fieldValues.monthlyRent) || '[AMOUNT]')} per month as rent for the Premises, payable in advance on the ${escapeHtml(String(fieldValues.rentDueDay) || '1st')} day of each calendar month. Rent shall be paid to Landlord at the following address: ${escapeHtml(String(fieldValues.landlordAddress) || '[ADDRESS]')} or such other place as Landlord may designate in writing.</p>
    <p>3.2 Late Payment Charges: If rent is not received by Landlord on or before the 5th day of the month, a late fee of $${escapeHtml(String(fieldValues.lateFeeAmount) || '[AMOUNT]')} shall be assessed and added to the rent due. Any grace period of ${escapeHtml(String(fieldValues.lateFeeDays) || '5')} days as referenced herein is a courtesy only and shall not constitute a waiver of the timely payment requirement or waive Landlord's right to pursue any legal remedies for non-payment.</p>
    <p>3.3 NSF Checks: A charge of $35 shall be assessed for each check returned for insufficient funds.</p>
    <p>3.4 Payment Method: All payments shall be made via check, money order, electronic transfer, or other method acceptable to Landlord. All payments are non-refundable.</p>

    <h2>4. SECURITY DEPOSIT</h2>
    <p>4.1 Amount: Tenant shall deposit with Landlord the sum of $${escapeHtml(String(fieldValues.securityDeposit) || '[AMOUNT]')} as a security deposit to be held by Landlord for the faithful performance of all terms and conditions of this Lease.</p>
    <p>4.2 Deposit Use: The security deposit may be applied by Landlord to any unpaid rent, damages to the Premises beyond normal wear and tear, cleaning costs, or any other default under this Lease. The security deposit shall not be considered rent, though it may be applied toward rent if Tenant defaults.</p>
    <p>4.3 Return of Deposit: Within ${stateId === 'UT' ? '30' : stateId === 'TX' ? '30' : stateId === 'ND' ? '30' : '30'} days after termination of the Lease and vacancy of the Premises, Landlord shall return the security deposit less any lawful deductions for damages, unpaid rent, or lease violations, along with an itemized statement of any deductions.</p>
    <p>4.4 Non-Refundable Fee: The security deposit is refundable only for damages and lease violations; it is NOT a non-refundable cleaning or administrative fee.</p>

    <h2>5. MAINTENANCE AND REPAIRS</h2>
    <p>5.1 Tenant Responsibilities: Tenant shall maintain the Premises in a clean, sanitary, and good condition and shall be responsible for all interior maintenance and minor repairs, including but not limited to: light bulbs, air filters, clogged drains, and routine maintenance costing less than $75.</p>
    <p>5.2 Landlord Responsibilities: Landlord shall maintain the structure, exterior, roof, foundation, and major systems (electrical, plumbing, heating/cooling) in good repair and comply with all applicable building, housing, and health codes.</p>
    <p>5.3 Repair Request Procedures: Tenant shall notify Landlord in writing of any necessary repairs within 48 hours of discovery. Landlord shall make repairs within a reasonable timeframe not to exceed 14 days for non-emergency situations.</p>
    <p>5.4 Emergency Repairs: In case of emergency (fire, flooding, gas leak, etc.), Tenant may arrange repairs and provide receipt to Landlord for reimbursement of reasonable costs.</p>

    <h2>6. ALTERATIONS AND IMPROVEMENTS</h2>
    <p>Tenant shall not make any alterations, additions, modifications, or improvements to the Premises, including but not limited to painting, installing shelving, hanging pictures with nails, installing fixtures, or landscaping, without prior written consent from Landlord. All alterations made without consent shall be deemed a material breach. All approved alterations become the property of Landlord and shall remain at the Premises upon termination of this Lease unless otherwise agreed in writing.</p>

    <h2>7. USE OF PREMISES</h2>
    <p>7.1 Permitted Use: The Premises shall be used solely as a residential dwelling unit for Tenant and approved occupants only. No business, trade, or commercial activity shall be conducted on the Premises.</p>
    <p>7.2 Prohibited Activities: Tenant shall not: (a) engage in any illegal activity; (b) maintain a dangerous, hazardous, or explosive substance; (c) keep any animal except as permitted in writing; (d) operate any motorized vehicle, motorcycle, or recreational vehicle on the Premises; (e) conduct any business operation; (f) create excessive noise; (g) engage in disorderly conduct.</p>
    <p>7.3 Nuisance Clause: Tenant shall not use the Premises in any way that creates a nuisance or materially interferes with the quiet enjoyment of neighboring tenants or surrounding properties.</p>

    <h2>8. PETS</h2>
    <p>No pets or animals of any kind shall be kept on the Premises without prior written permission from Landlord. If permission is granted, Tenant shall pay a pet deposit of $[PET DEPOSIT] and a monthly pet fee of $[PET FEE]. Tenant shall be liable for any and all damage caused by any pet, including excessive odor, stains, or removal of odor-causing conditions.</p>

    <h2>9. UTILITIES AND SERVICES</h2>
    <p>Tenant shall be responsible for arranging and paying for all utilities including: electricity, gas, water, sewer, trash collection, telephone, cable, and internet service. Landlord shall provide: [SPECIFY]. Tenant shall not alter or tamper with utility meters, systems, or connections.</p>

    <h2>10. INSURANCE</h2>
    <p>10.1 Renter's Insurance: Tenant shall obtain and maintain renter's insurance with minimum coverage of $[AMOUNT] throughout the term of this Lease. Proof of insurance shall be provided to Landlord within 14 days of Lease execution.</p>
    <p>10.2 Landlord's Insurance: Landlord shall maintain property insurance on the building structure only. Landlord's insurance does not cover Tenant's personal property or liability.</p>
    <p>10.3 No Liability: Landlord shall not be liable for any loss, theft, damage, or destruction of Tenant's personal property, regardless of cause.</p>

    <h2>11. NOISE AND CONDUCT</h2>
    <p>Tenant shall maintain peaceful and quiet enjoyment of the Premises and shall not create excessive noise between 10:00 PM and 8:00 AM, nor at any time constitute a nuisance to neighbors. Tenant shall comply with all local ordinances regarding noise levels and shall not have loud parties, loud music, or gatherings that disturb neighbors.</p>

    <h2>12. ENTRY AND INSPECTION</h2>
    <p>Landlord may enter the Premises for purposes of inspection, repair, maintenance, showing to prospective tenants, emergency situations, or other legitimate purposes upon reasonable notice (${stateId === 'UT' ? '24' : stateId === 'TX' ? '24' : stateId === 'ND' ? '24' : '24'} hours unless emergency). Tenant shall provide Landlord with keys and access codes. Landlord shall not unreasonably interfere with Tenant's quiet enjoyment of the Premises.</p>

    <h2>13. YARD AND LANDSCAPING</h2>
    <p>Tenant shall maintain any yard, patio, or outdoor area in a neat and clean condition. Tenant shall not alter landscaping without written permission. Tenant shall water vegetation regularly and maintain the grounds during the lease term.</p>

    <h2>14. PARKING</h2>
    <p>Tenant shall park vehicles only in assigned parking areas. No commercial vehicles, recreational vehicles, or inoperable vehicles may be parked on the Premises. Tenant shall not park on the street, grass, or common areas without express written permission. Violators are subject to towing at Tenant's expense.</p>

    <h2>15. TERMINATION AND RENEWAL</h2>
    <p>15.1 End of Term: Upon expiration of this Lease, Tenant shall vacate the Premises completely and return all keys. The Premises shall be in clean, undamaged condition (normal wear and tear excepted) or Tenant shall be liable for cleaning and repairs.</p>
    <p>15.2 Notice to Vacate: If either party wishes to terminate this Lease at its expiration date, written notice shall be provided no less than ${stateId === 'UT' ? '30' : stateId === 'TX' ? '30' : stateId === 'ND' ? '60' : '30'} days prior to the end of the lease term. Failure to provide notice may result in automatic renewal.</p>
    <p>15.3 Early Termination: Termination prior to the lease end date shall be considered a material breach. Tenant shall remain liable for all remaining rent owed unless Landlord re-rents the Premises.</p>

    <h2>16. DEFAULT AND REMEDIES</h2>
    <p>16.1 Default Events: The following shall constitute material default: (a) non-payment of rent or fees; (b) unauthorized occupants; (c) pets without permission; (d) alterations without consent; (e) illegal activity; (f) property damage; (g) violation of any lease term.</p>
    <p>16.2 Cure Period: If Tenant is in default, Landlord shall provide written notice with a reasonable opportunity to cure (minimum 3 days for non-payment, 5 days for other breaches) unless the breach cannot be cured (illegal activity).</p>
    <p>16.3 Remedies: Upon default, Landlord may: (a) apply security deposit; (b) pursue eviction proceedings; (c) recover all unpaid rent, late fees, court costs, and attorney fees; (d) hold Tenant liable for all damages to the Premises.</p>

    <h2>17. MOVE-OUT REQUIREMENTS</h2>
    <p>17.1 Final Inspection: Prior to move-out, Tenant shall notify Landlord and schedule a final walk-through inspection.</p>
    <p>17.2 Condition: The Premises shall be returned in the same condition as received, normal wear and tear excepted. All repairs needed shall be itemized and provided to Tenant.</p>
    <p>17.3 Cleaning: Tenant shall thoroughly clean the Premises including walls, floors, carpet, appliances, and removal of all personal items and trash. Professional cleaning may be required if condition is unsatisfactory.</p>
    <p>17.4 Keys and Access: All keys, remotes, access codes, and devices shall be returned in working condition. Lost keys will result in rekeying costs of $[AMOUNT] being deducted from security deposit.</p>

    <h2>18. FAIR HOUSING AND ANTI-DISCRIMINATION</h2>
    <p>Landlord shall not discriminate against Tenant based on protected class status including race, color, religion, sex, national origin, disability, familial status, or sexual orientation, in accordance with the Fair Housing Act and state laws.</p>

    ${getStateDisclosuresExpanded(stateId)}

    <h2>20. ENTIRE AGREEMENT AND MODIFICATIONS</h2>
    <p>This Lease constitutes the entire agreement between Landlord and Tenant and supersedes all prior negotiations and agreements, whether written or oral. This Lease may be modified only by written amendment signed by both Landlord and Tenant.</p>

    <h2>21. GOVERNING LAW</h2>
    <p>This Lease shall be governed by and construed in accordance with the laws of the State of ${stateId === 'UT' ? 'Utah' : stateId === 'TX' ? 'Texas' : stateId === 'ND' ? 'North Dakota' : 'South Dakota'}, without regard to conflict of law principles.</p>

    <h2>22. DISPUTE RESOLUTION</h2>
    <p>Any disputes arising from this Lease shall be resolved in the appropriate court of competent jurisdiction in the county where the Premises is located. Prevailing party in any litigation shall be entitled to recover reasonable attorney fees and court costs.</p>

    <h2>23. SEVERABILITY</h2>
    <p>If any provision of this Lease is found to be invalid or unenforceable, all other provisions shall remain in full force and effect.</p>

    <h2>24. LIABILITY WAIVER</h2>
    <p>Tenant acknowledges that Landlord is not liable for any loss of personal property, injury, or damage, regardless of cause, except as required by law. Tenant assumes full responsibility for all personal safety and security of the Premises.</p>
  `;
}

function getStateDisclosuresExpanded(stateId: string): string {
  const disclosures: Record<string, string> = {
    UT: `
      <h2>19. UTAH STATE-SPECIFIC PROVISIONS</h2>
      <h3>19.1 Fair Housing Disclosure</h3>
      <p>In accordance with the Utah Fair Housing Act (Utah Code § 34-42-1 et seq.), it is unlawful to refuse to rent, discriminate, or discriminate in advertising because of protected class status.</p>
      <h3>19.2 Radon Gas Disclosure</h3>
      <p>Radon is a naturally occurring radioactive gas that may accumulate in buildings in Utah. Long-term exposure may pose health risks. Testing for radon is recommended. Information about radon is available from the Utah Department of Environmental Quality.</p>
      <h3>19.3 Lead-Based Paint Disclosure (Pre-1978 Properties)</h3>
      <p>If the property was built before January 1, 1978, Landlord has disclosed all known information regarding lead-based paint and lead-based paint hazards. Tenant has been provided with the pamphlet "Protect Your Family from Lead in Your Home." Tenant acknowledges receipt of this disclosure.</p>
      <h3>19.4 Security Deposit Laws (Utah Code § 34-42-1)</h3>
      <p>Landlord shall return the security deposit within 30 days of lease termination with an itemized accounting of any deductions.</p>
    `,
    TX: `
      <h2>19. TEXAS STATE-SPECIFIC PROVISIONS</h2>
      <h3>19.1 Fair Housing Compliance</h3>
      <p>In accordance with the Texas Fair Housing Act and Texas Property Code § 92.001 et seq., it is unlawful to refuse to rent, negotiate, discriminate, or discriminate in advertising because of protected characteristics.</p>
      <h3>19.2 Lead-Based Paint Disclosure (Pre-1978 Properties)</h3>
      <p>If built before January 1, 1978, Landlord certifies disclosure of all known lead-based paint and lead-based paint hazards. Tenant has received the EPA pamphlet and has had 10 days to conduct an inspection.</p>
      <h3>19.3 Texas Property Code Compliance</h3>
      <p>This Lease is governed by Texas Property Code Chapter 92 (Residential Tenancies). Tenant rights and Landlord duties are established in this statutory framework. Both parties acknowledge familiarity with these rights and duties.</p>
      <h3>19.4 Security Deposit Handling (Texas Property Code § 92.103)</h3>
      <p>Landlord shall return the security deposit or provide an itemized accounting within 30 days of lease termination.</p>
      <h3>19.5 Mandatory Lease Language</h3>
      <p>Tenant is advised that Section 92.001, Texas Property Code grants certain rights and responsibilities to both Tenant and Landlord.</p>
    `,
    ND: `
      <h2>19. NORTH DAKOTA STATE-SPECIFIC PROVISIONS</h2>
      <h3>19.1 Fair Housing Notice</h3>
      <p>In accordance with North Dakota Fair Housing Act (N.D. Cent. Code § 14-02.4-01), it is unlawful to refuse to rent or discriminate because of protected status.</p>
      <h3>19.2 Security Deposit Requirements (N.D. Cent. Code § 47-16-01)</h3>
      <p>Landlord shall return the security deposit with interest within 30 days of lease termination. Deductions may only be made for damages beyond normal wear and tear, unpaid rent, or lease violations.</p>
      <h3>19.3 Lead-Based Paint Disclosure (Pre-1978 Properties)</h3>
      <p>If the property was built before January 1, 1978, Landlord discloses all known lead-based paint conditions and hazards in writing.</p>
      <h3>19.4 Right to Counsel</h3>
      <p>Tenant has the right to be represented by an attorney in any legal proceedings regarding this lease or tenancy.</p>
      <h3>19.5 Century Code Compliance</h3>
      <p>This Lease complies with North Dakota Century Code Chapter 47-16 (Residential Tenancies).</p>
    `,
    SD: `
      <h2>19. SOUTH DAKOTA STATE-SPECIFIC PROVISIONS</h2>
      <h3>19.1 Fair Housing Statement</h3>
      <p>Fair housing is a right guaranteed by state law (S.D. Codified Law § 20-13-1). It is unlawful to discriminate in rental housing based on protected characteristics.</p>
      <h3>19.2 Security Deposit Laws (S.D. Codified Law § 43-32-6)</h3>
      <p>Landlord shall return the security deposit within 14 days of lease termination with an accounting of any deductions for damages, cleaning, or unpaid rent.</p>
      <h3>19.3 Lead-Based Paint Disclosure (Pre-1978 Properties)</h3>
      <p>For properties built before January 1, 1978, Landlord certifies disclosure of all known lead-based paint hazards and has provided the EPA pamphlet to Tenant.</p>
      <h3>19.4 Codified Law Compliance</h3>
      <p>This Lease complies with South Dakota Codified Law Chapter 43-32 (Residential Tenancies).</p>
      <h3>19.5 Landlord Remedies</h3>
      <p>Landlord has the right to pursue all available remedies under state law for breach of this Lease, including eviction, suit for damages, and collection of all related costs and fees.</p>
    `
  };

  return disclosures[stateId] || `
    <h2>19. STANDARD DISCLOSURES</h2>
    <h3>Fair Housing Notice</h3>
    <p>This rental is offered without discrimination based on protected class status under applicable fair housing laws.</p>
  `;
}

function getStateDisclosures(stateId: string, templateTitle: string): string {
  // Check if this is a lease agreement
  if (templateTitle && (templateTitle.toLowerCase().includes('lease') || templateTitle.toLowerCase().includes('agreement'))) {
    return getComprehensiveLeaseContent(stateId, {});
  }
  
  const disclosures: Record<string, string> = {
    UT: `
      <h2>State-Specific Disclosures - Utah</h2>
      <p><strong>Fair Housing Act:</strong> It is illegal to discriminate in housing based on protected class status.</p>
      <p><strong>Radon:</strong> Radon is a naturally occurring radioactive gas that may accumulate in buildings.</p>
      <p><strong>Lead-Based Paint:</strong> For properties built before 1978, landlord must disclose all known lead-based paint hazards.</p>
    `,
    TX: `
      <h2>State-Specific Disclosures - Texas</h2>
      <p><strong>Fair Housing:</strong> Texas Property Code § 92.001 prohibits discrimination in rental housing.</p>
      <p><strong>Lead-Based Paint:</strong> Pre-1978 properties require disclosure of lead-based paint hazards per federal law.</p>
      <p><strong>Rights and Duties:</strong> See Texas Property Code Chapter 92 for tenant and landlord rights.</p>
    `,
    ND: `
      <h2>State-Specific Disclosures - North Dakota</h2>
      <p><strong>Fair Housing:</strong> N.D. Cent. Code § 14-02.4-01 prohibits discrimination in housing.</p>
      <p><strong>Security Deposits:</strong> Must be returned within 30 days per N.D. Cent. Code § 47-16-01.</p>
      <p><strong>Lead-Based Paint:</strong> Pre-1978 properties must have disclosed lead hazards.</p>
    `,
    SD: `
      <h2>State-Specific Disclosures - South Dakota</h2>
      <p><strong>Fair Housing:</strong> S.D. Codified Law § 20-13-1 prohibits rental discrimination.</p>
      <p><strong>Security Deposits:</strong> Must be returned within 14 days per S.D. Codified Law § 43-32-6.</p>
      <p><strong>Lead-Based Paint:</strong> Pre-1978 properties require lead hazard disclosure.</p>
    `
  };

  return disclosures[stateId] || `
    <h2>Mandatory Disclosures</h2>
    <p><strong>Fair Housing:</strong> Housing offered without discrimination based on protected status.</p>
  `;
}

function generateDefaultTemplateContent(
  safeTitle: string,
  fieldValues: FieldValue,
  safeStateId: string
): string {
  // Generate a default template based on common patterns
  // NOTE: safeTitle and safeStateId are already HTML-escaped
  const sections: string[] = [];
  
  sections.push(`<h1>${safeTitle}</h1>`);
  
  // Group fields by category
  const categories = new Map<string, Array<[string, any]>>();
  
  Object.entries(fieldValues).forEach(([fieldId, value]) => {
    // Infer category from field ID (simple heuristic)
    let category = 'General Information';
    if (fieldId.includes('landlord')) category = 'Landlord Information';
    else if (fieldId.includes('tenant')) category = 'Tenant Information';
    else if (fieldId.includes('property')) category = 'Property Details';
    else if (fieldId.includes('rent') || fieldId.includes('deposit') || fieldId.includes('fee')) category = 'Financial Terms';
    else if (fieldId.includes('lease') || fieldId.includes('date')) category = 'Lease Terms';
    
    if (!categories.has(category)) {
      categories.set(category, []);
    }
    categories.get(category)!.push([fieldId, value]);
  });
  
  // Generate sections (with HTML escaping for security)
  categories.forEach((fields, category) => {
    const safeCategory = escapeHtml(category);
    sections.push(`<h2>${safeCategory}</h2>`);
    fields.forEach(([fieldId, value]) => {
      const label = fieldIdToLabel(fieldId);
      const safeLabel = escapeHtml(label);
      const safeValue = escapeHtml(String(value));
      sections.push(`<p><strong>${safeLabel}:</strong> <span class="field-value">${safeValue}</span></p>`);
    });
  });
  
  // Add comprehensive content for lease agreements
  const titleLower = safeTitle.toLowerCase();
  if (titleLower.includes('lease') || titleLower.includes('agreement')) {
    // Replace with full comprehensive lease content
    return getComprehensiveLeaseContent(safeStateId, fieldValues);
  }
  
  // Add state-specific disclosures for other documents
  if (titleLower.includes('rental application') || titleLower.includes('notice') ||
      titleLower.includes('checklist')) {
    sections.push(getStateDisclosures(safeStateId, safeTitle));
  }
  
  // Add signature blocks for leases and agreements
  if (titleLower.includes('lease') || titleLower.includes('agreement')) {
    sections.push(`
      <div class="signature-block">
        <h2>Signatures</h2>
        <p>By signing below, the parties acknowledge that they have read, understood, and agree to the terms outlined in this document.</p>
        
        <p style="margin-top: 30pt;">
          <strong>Landlord:</strong><br>
          Signature: <span class="signature-line"></span><br>
          Date: _________________
        </p>
        
        <p style="margin-top: 30pt;">
          <strong>Tenant:</strong><br>
          Signature: <span class="signature-line"></span><br>
          Date: _________________
        </p>
      </div>
    `);
  }
  
  return sections.join('\n');
}

function fieldIdToLabel(fieldId: string): string {
  // Convert camelCase to Title Case
  return fieldId
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (str) => str.toUpperCase())
    .trim();
}
